### ISSUE TITLE
Add API to allow users to query hotels

### ISSUE THREAD

**Issue by alicel** [hemidactylus/hotels_llm_demo#4]
Simplest possible hotel query by location. We might consider adding something like "type of booking" to allow the user to specify if this is a business booking / family booking etc (unless we derive this just from the profile).

**Comment by hemidactylus** [comment]
Usually this is how I would factor: a function in the "dbio" layer (between endpoint and CQL) that has booking type as explicit argument, and then decide later if exposed in the endpoint or automatically inferred from e.g. "user_id" in the search_hotel request
